name: Tests
on:
  push:

jobs:
  tests:
    name: "Run Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Install Task
        uses: arduino/setup-task@v1

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.4

      - name: Install Dependencies
        run: go mod download
        working-directory: ./

      - name: Go Vet
        run: go vet ./...
        working-directory: ./

      - name: Run tests
        run: go test -v -tags test -failfast ./...
        working-directory: ./
        env:
          DUFFEL_TOKEN: duffel_test_123
